### ISSUE TITLE
I can't get dehaze results. 

### ISSUE THREAD

**Issue by cengj3k** [liuh127/Two-branch-dehazing#2]
When I ran test.py according to your instructions, I got message as 'Name Error: name 'hazy_up' is not defined.'.

When I 'hazy_up' was modified to'hazy' and executed, it was executed, but the normal result could not be obtained.
I replace the'hazy_up' variable to'hazy' and ran test.py, but the output image did not original image or dehaze image.

How do I get dehaze image with your learning model and code?

**Comment by LeoYu97** [comment]
I suggest checking the location of ‘best.pkl’ and ’NTIRE2021_Test_Hazy’. This problem may be caused by not loading our model weights.

**Comment by cengj3k** [comment]
thank you!
