### ISSUE TITLE
the question of dataset

### ISSUE THREAD

**Issue by Kayla2714** [liuh127/Two-branch-dehazing#5]
Excuse me,I just don't understand  the dataset you provided.I wonder the dataset which contains 80 images is composed of which dataset?And how many of each?
Would you please introduce it in detail？Thanks a lot!

**Comment by liuh127** [comment]
Hi,
The dataset  is composed of NH-HAZE-20 and NH-HAZE-21. Please refer to our paper for more details.

**Comment by liuh127** [comment]
> Excuse me,I just don't understand the dataset you provided.I wonder the dataset which contains 80 images is composed of which dataset?And how many of each?
> Would you please introduce it in detail？Thanks a lot!

Hi,
The dataset is composed of NH-HAZE-20 and NH-HAZE-21. Please refer to our paper for more details.

**Comment by Kayla2714** [comment]
Happy to receive your reply .And I want to say that I have read the paper ， I remember that you wrote such a sentence in it：We conduct experiments on these datasets separately.But in this dataset they are integrated together.That’s what makes me confused .
