### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Kayla2714** [liuh127/Two-branch-dehazing#6]
尊敬的作者您好，我有一个问题想请教一下，您的数据集显示您将NH2020和NH2021数据集合并了起来，请问在训练时也是直接一起训练这80张图片的吗？
Dear author, I have a question of the dataset. Your dataset shows that you have combined NH2020 and NH2021 datasets. Do you also directly train these 80 pictures together during training?

那么Dense-haze数据集和O-haze数据集又是如何训练的呢？
If so, how are dense-haze datasets and o-haze datasets trained?

顺便问一句：您每个数据集训练多少轮呢？
By the way，how many epochs did you train ?

**Comment by liuh127** [comment]
> 尊敬的作者您好，我有一个问题想请教一下，您的数据集显示您将NH2020和NH2021数据集合并了起来，请问在训练时也是直接一起训练这80张图片的吗？
> Dear author, I have a question of the dataset. Your dataset shows that you have combined NH2020 and NH2021 datasets. Do you also directly train these 80 pictures together during training?
> 
> 那么Dense-haze数据集和O-haze数据集又是如何训练的呢？
> If so, how are dense-haze datasets and o-haze datasets trained?
> 
> 顺便问一句：您每个数据集训练多少轮呢？
> By the way，how many epochs did you train ?

Hi,

To be precise, the dataset we upload is used during the NTIRE 2021 competition, in which we train our model with all the available data from NH-HAZE2020 and NH-HAZE2021. The test set in the uploaded drive aims to provide training accuracy rather than test accuracy. The final test accuracy of our model for this challenge is obtained from the official online server.

If you want to run experiments on every single dataset(RESIDE, O-HAZE, Dense-haze, nh-haze2020, nh-haze-2021), please follow the intros in section 4.1. We follow the official train, val and test split if there are. For NH-HAZE-2021, the official val and test data didn't have been released at the time when we submitted our manuscript. Thus, we self-constructed a train, test split on NH-HAZE-2021.

**Comment by Kayla2714** [comment]
> > 尊敬的作者您好，我有一个问题想请教一下，您的数据集显示您将NH2020和NH2021数据集合并了起来，请问在训练时也是直接一起训练这80张图片的吗？
> > Dear author, I have a question of the dataset. Your dataset shows that you have combined NH2020 and NH2021 datasets. Do you also directly train these 80 pictures together during training?
> > 那么Dense-haze数据集和O-haze数据集又是如何训练的呢？
> > If so, how are dense-haze datasets and o-haze datasets trained?
> > 顺便问一句：您每个数据集训练多少轮呢？
> > By the way，how many epochs did you train ?
> 
> Hi,
> 
> To be precise, the dataset we upload is used during the NTIRE 2021 competition, in which we train our model with all the available data from NH-HAZE2020 and NH-HAZE2021. The test set in the uploaded drive aims to provide training accuracy rather than test accuracy. The final test accuracy of our model for this challenge is obtained from the official online server.
> 
> If you want to run experiments on every single dataset(RESIDE, O-HAZE, Dense-haze, nh-haze2020, nh-haze-2021), please follow the intros in section 4.1. We follow the official train, val and test split if there are. For NH-HAZE-2021, the official val and test data didn't have been released at the time when we submitted our manuscript. Thus, we self-constructed a train, test split on NH-HAZE-2021.

So does the quantitative comparisons (table3) in your paper represent the results of separate training ?

**Comment by liuh127** [comment]
> > > 尊敬的作者您好，我有一个问题想请教一下，您的数据集显示您将NH2020和NH2021数据集合并了起来，请问在训练时也是直接一起训练这80张图片的吗？
> > > Dear author, I have a question of the dataset. Your dataset shows that you have combined NH2020 and NH2021 datasets. Do you also directly train these 80 pictures together during training?
> > > 那么Dense-haze数据集和O-haze数据集又是如何训练的呢？
> > > If so, how are dense-haze datasets and o-haze datasets trained?
> > > 顺便问一句：您每个数据集训练多少轮呢？
> > > By the way，how many epochs did you train ?
> > 
> > 
> > Hi,
> > To be precise, the dataset we upload is used during the NTIRE 2021 competition, in which we train our model with all the available data from NH-HAZE2020 and NH-HAZE2021. The test set in the uploaded drive aims to provide training accuracy rather than test accuracy. The final test accuracy of our model for this challenge is obtained from the official online server.
> > If you want to run experiments on every single dataset(RESIDE, O-HAZE, Dense-haze, nh-haze2020, nh-haze-2021), please follow the intros in section 4.1. We follow the official train, val and test split if there are. For NH-HAZE-2021, the official val and test data didn't have been released at the time when we submitted our manuscript. Thus, we self-constructed a train, test split on NH-HAZE-2021.
> 
> So does the quantitative comparisons (table3) in your paper represent the results of separate training ?

yes
